In [132]:
# 과학 파이썬. https://www.scipy.org/
# 넘파이 입문. https://numpy.org/doc/1.20/user/absolute_beginners.html



import numpy as np

AA = np.array([[1,2],[3,4]])
BB = np.array([[2,2],[2,2]])
AA*BB

array([[2, 4],
       [6, 8]])

In [133]:
AA = np.array([[1,2],[3,4]])
BB = np.array([[2,4],[2,2]])
C = AA*BB
D = 2*AA

print(C)
print(D)

[[2 8]
 [6 8]]
[[2 4]
 [6 8]]


In [134]:
# x = np.array([
#              e,
#              f
#             ])

# A = np.array([[a,b],
#             [c,d]])

# A*x = ([[a*e, b*f],
#        [c*e, d*f]])

In [135]:
A = D
x = np.array([1,2])

In [136]:
np.dot(A,x)

array([10, 22])

In [137]:
A[0,0]*x[0] + A[0,1]*x[1]

10

In [138]:
A[1,0]*x[0] + A[1,1]*x[1]

22

In [139]:
# [e, f]*[[a, b],[c, d]]

np.dot(x,A)

array([14, 20])

In [140]:
x[0]*A[0,0] + x[1]*A[1,0]

14

In [141]:
x[0]*A[0,1] + x[1]*A[1,1]

20

In [142]:
# a1, a2는 상수.
# A*(a1*x1 + a2*x2) = a1*A*x1 + a2*A*x2

In [143]:
e1 = np.array([1,0]) ; e2 = np.array([0,1])
x = e1 + 2*e2
x

array([1, 2])

In [144]:
# np.dot(A,x) = np.dot(A,e1) + 2*np.dot(A,e2)

In [145]:
b1 = np.array([2,6])
b2 = 2*np.array([4,8])

b1+b2

array([10, 22])

In [146]:
# 1. A = [[1,2],
#        [0,2]]
# x1 = [1,1]
# x2 = [3,2]

A = np.array([[1,2],[0,2]])
x = np.array([1,1])

sol1 = np.dot(A,x)

x2 = np.array([3,2])
sol2 = np.dot(A,x2)

In [147]:
a11 = 2; a12 = 6
a21 = 4; a22 = 8

b1 = 5; b2 = 3

# 연립방정식
# a11*x1 + a12*x2 = b1
# a21*x1 + a22*x2 = b2

A = np.array([[a11,a12],
              [a21,a22]])

# x = ?

b = np.array([5,3])

x = np.linalg.solve(A,b)
print('x',x)

x [-2.75  1.75]


In [148]:
# 머리가 36개, 발이 92개일 때, 토끼와 닭이 몇 마리인지 찾으시오.

Sol1 = np.array([[1,1],
                 [4,2]])
sol1 = np.array([36,92])

sol = np.linalg.solve(Sol1,sol1)
print('sol',sol)

sol [10. 26.]


# Homework

In [149]:
# 100마리 양을 구매하려는데 10,000,000원이 있다.
# 숫양은 200,000원, 암양은 100,000원, 어린양은 100,000/3원이다.
# 돈을 다 소진하려면 숫양, 암양, 어린양의 수가 몇이어야 하는가?

# x + y + z = 100
# 2*x + y + z/3 = 100


for i in range(1,33):
    Sol2 = np.array([[1,1],
                   [2,1]])
    sol2 = np.array([100-(3*i),100-i])
    sol = np.linalg.solve(Sol2,sol2)
    sol = np.append(sol,3*i)
    print('숫양, 암양, 어린양: ', sol)

숫양, 암양, 어린양:  [ 2. 95.  3.]
숫양, 암양, 어린양:  [ 4. 90.  6.]
숫양, 암양, 어린양:  [ 6. 85.  9.]
숫양, 암양, 어린양:  [ 8. 80. 12.]
숫양, 암양, 어린양:  [10. 75. 15.]
숫양, 암양, 어린양:  [12. 70. 18.]
숫양, 암양, 어린양:  [14. 65. 21.]
숫양, 암양, 어린양:  [16. 60. 24.]
숫양, 암양, 어린양:  [18. 55. 27.]
숫양, 암양, 어린양:  [20. 50. 30.]
숫양, 암양, 어린양:  [22. 45. 33.]
숫양, 암양, 어린양:  [24. 40. 36.]
숫양, 암양, 어린양:  [26. 35. 39.]
숫양, 암양, 어린양:  [28. 30. 42.]
숫양, 암양, 어린양:  [30. 25. 45.]
숫양, 암양, 어린양:  [32. 20. 48.]
숫양, 암양, 어린양:  [34. 15. 51.]
숫양, 암양, 어린양:  [36. 10. 54.]
숫양, 암양, 어린양:  [38.  5. 57.]
숫양, 암양, 어린양:  [40.  0. 60.]
숫양, 암양, 어린양:  [42. -5. 63.]
숫양, 암양, 어린양:  [ 44. -10.  66.]
숫양, 암양, 어린양:  [ 46. -15.  69.]
숫양, 암양, 어린양:  [ 48. -20.  72.]
숫양, 암양, 어린양:  [ 50. -25.  75.]
숫양, 암양, 어린양:  [ 52. -30.  78.]
숫양, 암양, 어린양:  [ 54. -35.  81.]
숫양, 암양, 어린양:  [ 56. -40.  84.]
숫양, 암양, 어린양:  [ 58. -45.  87.]
숫양, 암양, 어린양:  [ 60. -50.  90.]
숫양, 암양, 어린양:  [ 62. -55.  93.]
숫양, 암양, 어린양:  [ 64. -60.  96.]


# Problem

균일한 속도로 걸어가는 A와 B가 있다.
1. 마주보며 100미터 거리를 좁혀오고 있을 때 만나는 데 걸리는 시간은 30초다.
2. 똑같은 방향으로 걸어가고 있을 때 A가 B를 따라잡는 데 걸리는 시간은 80초다.

문제: A와 B의 속력을 찾아라.

    거리 = 속력*시간
    d = v*t


In [150]:
# vA*30s + vB*30s = 100m
# vA*80s - vB*80s = 100m

t = np.array([[30, 30],
              [80, -80]])
d = np.array([100, 100])

v = np.linalg.solve(t,d)
print('v_A, v_B: ', v)

v_A, v_B:  [2.29166667 1.04166667]


# Problem 2

A가 초속 2m, B가 초속 1m로 걸어가고 있다. 초기 거리는 100미터이다.
서로 만날 때까지 걸리는 시간은?

가) 서로 마주보며 걸을 때

2*t = 100 - 1*t
3*t = 100 -> t = 100/3
3*t - 100 = 0 # Equation to solve

나) 같은 방향으로 걸을 때

In [151]:
from sympy import *

t1, t2 = symbols('t1 t2')

eq1 = 2*t1 + 1*t1 - 100
eq2 = 2*t2 - 1*t2 - 100

print('가: ', solve(eq1), ', 나: ', solve(eq2))

가:  [100/3] , 나:  [100]


### 

A*x = b

Inverse matrix definition A^(-1)*A = 1
A^(-1)*A*x = A^(-1)*b

We can solve for x if we know the matrix

In [152]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[-1.    0.75]
 [ 0.5  -0.25]]


In [153]:
np.dot(Ainv,[100,100]) # Another way of solving

array([-25.,  25.])

In [171]:
# 다음과 같은 벡터가 주어졌을 때
u = [1,1]
v = [1,-1]

# 다음 연산을 충족시키는 A 행렬을 찾으시오.
# np.matmul(A,u) = [3,2]
# np.matmul(A,v) = [-1,-2]

# Find A

# 1) 단위벡터 사용
# np.dot(A,[1,0]) = 첫번째 열
# np.dot(A,[0,1]) = 두번째 열

# 단위벡터에 적용하는 연산자의 답은 연산자 자체의 열이 된다.
# A*(u+v) = 2*A*[1,0] = [2,0]
# A*(u-v) = 2*A*[0,1] = [4,4]

A1 = [1,0] # Column vectors 열
A2 = [2,2]
A = np.array([[1,2],
              [0,2]])

In [172]:
np.dot(A,u)

array([3, 2])

In [173]:
np.dot(A,v)

array([-1, -2])

In [121]:
import numpy as np

A = np.array([[30,30],[40,80]])
np.linalg.det(A)

1200.0

# 

A와 B의 공식: 30x1 + 30x2 = 100

x1 -> y, x2 -> x

30y = -30x + 100y = m*x + a 형태로 쓸 수가 있음

# 선의 공식

#### y = -x + 100/30

In [127]:
import matplotlib.pyplot as plt

# y 함수 정의

def y(x):
    return -x+100/30

In [128]:
x = np.linspace(-100,100,20)