In [1]:
import numpy as np

AA = np.array([[1,2],[3,4]])
BB = np.array([[2,2],[2,2]])

AA*BB

In [2]:
x = np.array([1,2])
A = np.array([[2,4],
              [6,8]])

# a1, a2는 상수
# A*(a1*x1 + a2*x2) = a1*A*x1 + a2*A*x2

In [3]:
# x = a1*e1 + a2*e2
e1 = np.array([1,0]); e2 = np.array([0.1])

In [4]:
x = e1 + 2*e2

In [5]:
# np.dot(A,x) = np.dot(A,e1) + 2*np.odt(A,e2)

In [6]:
b1 = np.array([2,6])
b2 = 2*np.array([4,8])

In [9]:
b1 + b2 = [10,22]

x=[1,2], A*x = [10,22]
# A의 값은?
# 1. 연립방정식을 이용해 풀기
# 2. 단위벡터를 대입한 후 풀기

# 1. A = [[1,2],
#        [0,2] 이고
#    x = [1,1] 일때 A*x를 찾으시오
# 2. x = [3,2]

SyntaxError: can't assign to operator (<ipython-input-9-8d226fc8da52>, line 1)

In [12]:
A = np.array([[1,2],[0,2]])
x = np.array([1,1])

sol1 = np.dot(A,x)

x2 = np.array([3,2])
sol2 = np.dot(A,x2)


array([7, 4])

In [17]:
a11 = 2; a12 = 6
a21 = 4; a22 = 8

b1 = 5; b2 = 3


# 연립방정식
#a11*x1 + a12*x2 = b1
#a21*x1 + a22*x2 = b2

A = np.array([[a11,a12],
              [a21,a22]])
# x = ?
b = np.array([5,3])

x = np.linalg.solve(A,b)
print('x',x)

x [-2.75  1.75]


In [19]:
#
# 머리가 36개, 발이 92개일때 토끼와 닭이 몇마리인지 찾으시오
#
# 힌트. 

A = np.array([[1,1],[4,2]])
b = np.array([36,92])

x = np.linalg.solve(A,b)
print('x',x)

x [10. 26.]


In [21]:
# 100마리 양을 구매하려는데 10,000,000 원이 있다.
# 숫양 은 200,000원, 암양은 100,000원, 어린양은 100,000/3 원이다.
# 돈을 다 소진 하려면 숫양, 암양, 어린양의 수가 몇이어야 하는가?
# 양 숫자가 0이 될 수는 없다. 많은 경우의 수가 가능함. 그리고 양의 숫자는 정수.

A = np.array([[1,1,1],[200000,100000,100000/3]])
b = np.array([100,10000000])

number = 0
for i in range(0,100):
    number = number + 1
    
x = np.linalg.solve(A,b)

print('x',x)

IndentationError: expected an indented block (<ipython-input-21-c7165904ce09>, line 10)

In [24]:
from IPython.display import Image

## 아무개 A, 범진 B 씨가 있다.
1. 서로 마주보며 균일한 속도로 걸어오며 100m 거리를 좁혀오고 있다. 30초가 걸린다. 
2. 서로 똑같은 방향으로 걸어가고 있을 때 아무개씨가 범진씨를 따라 잡을때까지 걸리는 시간은 80초 이다.

아무개씨와 범진씨의 속력을 찾아라
  
   거리 = 속도 * 시간  
   d = v * t
   
   ![title](Lecture1/image_2021-02-02_14-49-31.png)

In [23]:
A = np.array([[30,30],[80,-80]])
b = np.array([100,100])

x = np.linalg.solve(A,b)

print('아무개의 속력, 범진의 속력',x)

아무개의 속력, 범진의 속력 [2.29166667 1.04166667]


아무개씨가 초속 2미터로 걸어가고 있다.  
범진씨는 초속 1미터 속력으로 걸어가고 있다.  
서로 만날때까지 걸리는 시간을 찾으시오.  
초기 거리는 100미터이다.  

가) 서로 마주보며 걸을 때  

2 * t1 + 1 * t1 = 100  
3 * t1 = 100  

나) 같은 방향으로 걸을 때  

2 * t2 - 1 * t2 = 100

In [ ]:
행렬식 = determinant ~ 면적을 구하는 연산
M by N matrix, M=N determinant 가 가능함


In [25]:
A = np.array([[30,30],[80,-80]])

In [26]:
np.linalg.det(A)

-4800.000000000001

In [ ]:
parallelepiped 평행

30*x1 + 30*x2 = 100

x1 -> y  
x2 -> x

30*y = -30*x + 100  
y = m*x + a 의 형태로 쓸 수 가 있음

### 선의 공식
y = -x + 100/30


In [29]:
import matplotlib.pyplot as plt

# y 함수 정의
def y(x):
    return -x + 100/30

In [30]:
x = np.linspace(-100,100,20)

In [31]:
Ainv = np.linalg.inv(A)

In [32]:
print(Ainv)

[[ 0.01666667  0.00625   ]
 [ 0.01666667 -0.00625   ]]


In [33]:
np.dot(Ainv, A)

array([[1., 0.],
       [0., 1.]])

In [36]:
# 다음과 같은 벡터가 주어졌을 때
u = [1,1]
v = [1,-1]

# 다음 연산을 충족시키는 A 행렬을 찾으시오
matmul(A,u) = np.array([3,2])
matmul(A,v) = np.array([-1,-2])

#Find A
np.dot(A,[1,0]) = 첫번째 열
np.dot(A,[0,1]) = 두번째 열

A*(u + v) = 2*A*[1,0] = [2, 0]
A*(u - v) = 2*A*[0,1] = [4, 4]

A1 = [1,0] # Column vector 첫번째 열
A2 = [2,2] # Colunm vector 두번째 열

A = np.array([[1,2],
              [0,2]])

SyntaxError: can't assign to function call (<ipython-input-36-208d915a9310>, line 6)

In [37]:
A = np.array([[1,2],[0,2]])
np.dot(A,[1,1])

array([3, 2])

In [38]:
np.dot(A,[1,-1])

array([-1, -2])